### ISSUE TITLE
Consider dual license

### ISSUE THREAD

**Issue by dyedgreen** [Gopiandcode/petrol#5]
Would you consider / be open to dual licensing this project to also be available under a more permissive license like MIT / Apache?

I’m interested in using it (and contributed the necessary changes for #2, to make it work for my use-case), but having a less restrictive license would make it much easier for me to integrate with my existing projects 😅

**Comment by kiranandcode** [comment]
Hi @dyedgreen ! Yes, I would be open to dual-licensing/re-licensing under a more permissive license. I had intended this library to be used by the community, so had chosen a more liberal license (LGPL) than my usual projects.

That being said, as a double check, are you sure you need an Apache License? The LGPL is already fairly permissive[1] --- AFAIK (happy to be corrected), you can still build MIT/proprietary software using libraries under LGPL licenses like petrol, the main constraint that the LGPL enforces is that changes to the library itself must be made as LGPL.

In your case, your projects using petrol/your modified version of petrol, can still be licensed however you want, the only constraint is that your modification has to be LGPL licensed.

That's how I understand it --- if this is your understanding but you still need petrol to be more permissively licensed, or if my understanding is wrong, please let me know, and I'd be happy to relicense it under a more permissive license.

[1] It's also not an uncommon license in the OCaml ecosystem --- the compiler itself is licensed under LGPL.

**Comment by dyedgreen** [comment]
Ah that makes sense; I think you’re right that there is an explicit exemption for being allowed to link against the library as part of a bigger project. (But I’m not a layer so not legal advice 🙈)

I think that in this case the current license would probably work for me!

(Although I’ve heard of cases where it did not work which was my main concern; afaik it can be hard to change licenses once there are contributions by others, since you need to get every contributors permission; but I’ll leave it to you to decide, if I understand correctly now I would be able to use the library either way 😊)

**Comment by dyedgreen** [comment]
Hey, just to check in on the open issue: Do you want to dual license the project under something like MIT/Apache? Otherwise I'll go ahead and close the issue 😅

**Comment by kiranandcode** [comment]
Ah yep, sorry.

I guess I'll leave it as LGPL for now (as the OCaml stlib is also similarly licensed, so likely any program using Petrol will be compatible).

If someone has a strong preference for a more Liberal license, we can consider relicensing then.
